---
name: Build

# yamllint disable-line rule:truthy
on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - run: npm ci
      - run: npm run build
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
      # - run: npm test
